# Generated by Django 4.2.1 on 2023-06-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_genre_song_remove_genre_songs_song_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
    ]
